- name: Copy WAR file to web servers
  hosts: web
  become: yes
  tasks:
    - name: Copy WAR file
      copy: 
        src: /home/devops/slavedata/workspace/Pipeline_sonar/target/addressbook.war 
        dest: /opt/tomcat/webapps  
        owner: tomcat 
        group: tomcat
    - name: start the tomcat process 
      shell: sudo su tomcat -c '/opt/tomcat/bin/shutdown.sh'
      shell: sudo su tomcat -c '/opt/tomcat/bin/startup.sh'
