- name: App deploy kubernetes
  hosts: kube
  become: yes
  tasks:
    - name: App deploy
      shell: kubectl apply -f https://raw.githubusercontent.com/Sanjiban2332/JavaProjectDeploy/master/KubeDeploy.yml
