apiVersion: apps/v1
kind: Deployment
metadata:
  name: addressbook-app
  labels:
    app: addressbook
spec:
  replicas: 4
  selector:
    matchLabels:
      app: addressbook
  template:
    metadata:
      labels:
        app: addressbook
    spec:
      containers:
      - name: addressbook
        image: sanjirath/addressbook:latest
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: addressbook-service
spec:
  type: NodePort
  selector:
    app: addressbook
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 32105
